### ISSUE TITLE
publish (zkSNACKs) PGP key block on website

### ISSUE THREAD

**Issue by MarnixCroes** [zkSNACKs/WasabiWalletWebSite#13]
Instead of having it only listed on github walletwasabi repo

**Comment by kristapsk** [comment]
What do you mean? There is PGP fingerprint in website with link to full pubkey.

![image](https://github.com/zkSNACKs/WasabiWalletWebSite/assets/4500994/4521f22c-3263-4956-afa1-ff01a43794e7)

**Comment by MarnixCroes** [comment]
>  with link to full pubkey.

I didn't know that is has a link, thanks
that's good.

> What do you mean?

In general, I don't really see harm to not also list full pubkey on the website. 
the less dependece on github, the better (for this one, as long as we also use github links for the download button, it's not that much of an improvement though)

And might be easier (UX) for newbs as well. That they don't have to go to github at all.
Only click buttons on the website itself.

anyway, I didn't know about the link, that's already an improvement

**Comment by kristapsk** [comment]
> anyway, I didn't know about the link, that's already an improvement

It's only over letters "PGP", not the full fingerprint. Maybe it's better to have whole line clickable.

Also, it currently points to https://github.com/zkSNACKs/WalletWasabi/blob/master/PGP.txt, but likely it's better to point to https://raw.githubusercontent.com/zkSNACKs/WalletWasabi/master/PGP.txt.

**Comment by MarnixCroes** [comment]
the issue is still valid imo,
unless it is nacked
