### ISSUE TITLE
Feature Request: Trigger CloudFlare Cache Flush on Website Deployment

### ISSUE THREAD

**Issue by CAnorbo** [zkSNACKs/WasabiWalletWebSite#30]
**Problem Statement:**
Currently, after deploying updates to our website, the changes are not immediately reflected to the end-users due to caching by CloudFlare. This delay in content update visibility can sometimes lead to confusion among users and stakeholders, especially when critical updates like new software version or fixes are deployed.

**Proposed Solution:**
I would like to propose the integration of a feature or a workflow within our deployment process that automatically triggers a CloudFlare cache flush immediately after a deployment is completed. This would ensure that all users see the most recent version of the website without any manual intervention required to clear the cache.

**Benefits:**

- Immediate Content Updates: Ensures that any updates or changes to the website are immediately visible to all users.
- Reduced Manual Work: Automates the cache clearing process, reducing the need for manual intervention and the potential for human error.
- Enhanced User Experience: Provides a better experience for the end-user by displaying the most current content without delays.

**Considerations:**

- We need to assess the impact of more frequent cache clearing on our website's performance and loading times.
- It's important to ensure that the cache flush is strategically targeted to affected resources to minimize unnecessary performance impacts.

**Comment by molnard** [comment]
cACK

**Comment by kristapsk** [comment]
https://developers.cloudflare.com/workers/runtime-apis/cache/

https://developer.mozilla.org/en-US/docs/Web/API/Cache

**Comment by lontivero** [comment]
Http protocol cache infrastructure is controlled by the `Cache-Control` header + validation. Flushing cloudflare doesn't solve the problem, instead it can make things worse for us. I suggest to close this issue and open one with the title "Reflect changes in website immediately (cache)"
