### ISSUE TITLE
Adding branch protection to `master` branch

### ISSUE THREAD

**Issue by kristapsk** [zkSNACKs/WasabiWalletWebSite#4]
As we auto deploy on commits in `master`, I think we should look at adding some GitHub restrictions to it.

IMO no direct commits to `master` branch should be allowed, instead it should be forced through PRs with at least ACK review.

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches

**Comment by nopara73** [comment]
![image](https://github.com/zkSNACKs/WasabiWalletWebSite/assets/9156103/790601fd-8c82-4bb9-9cb8-3bc12febbadf)

**Comment by molnard** [comment]
Done

**Comment by kristapsk** [comment]
Tested, works.
```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Changes must be made through a pull request.
To github.com:zkSNACKs/WasabiWalletWebSite.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:zkSNACKs/WasabiWalletWebSite.git'
```
