### ISSUE TITLE
Host binaries on website directly instead of linking to GitHub

### ISSUE THREAD

**Issue by MarnixCroes** [zkSNACKs/WasabiWalletWebSite#8]
On the website the download button of a package links to GitHub, to download the package.
We could/should host the binaries on the website itself instead of linking to GitHub.

### Pros
- less dependence on GitHub
- no user ip address leaking to GitHub
### Cons
- Website being compromised could lead to replacement of binaries with a malicious one
(but the same is true for current, where the link could be replaced)

I think these are the main pros and cons. Please comment if you think there are others worth mentioning

**Comment by kristapsk** [comment]
> * Website being compromised could lead to replacement of binaries with a malicious one
>   (but the same is true for current, where the link could be replaced)

I'm wondering could we add some GPG singnature validation on server side? Would that be worth doing? (could be simple - if signature is wrong, let's just bring whole website down and alert everybody!) Replacing files in release page on GitHub or in this website GitHub repo should be simpler than getting access to private key to sign binaries.

Another idea (but that's more related to release process as a whole, not just website change) - release binaries could be timestamped with OpenTimestamps, which relies on security of Bitcoin blockchain, that would allow to detect if binaries presented to user are replaced at later date after release.

**Comment by nopara73** [comment]
In my analysis, there seem to be zero pros, only cons?

> no user ip address leaking to GitHub

That's no pro. It'd leak to us, which is no better. The only way to avoid it is by using Tor Browser.

> less dependence on GitHub

That seems irrelevant as well. If GitHub kills us, we can do something, but it might just kill us. It's almost indispensable, and not hosting binaries there would make little difference.

Another weak con, although very similar to the previous one, is that the website hosts a PGP fingerprint, which saves vigilant users from attacks: they must cross-check GitHub binaries against the website's fingerprint. However, assuming we'd start hosting the binaries on the website, a (sophisticated) attack on the website may replace not only the binaries but also the fingerprint.

**Comment by molnard** [comment]
I agree with nopara here. There is an exchange of responsibility - but nothing changes. If we ever touch this we need to have a strong reason.
